# Generated by Django 3.0.4 on 2021-06-29 19:42

import backend.models
import backend.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='content',
            name='additional_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='copyright_approved',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='content',
            name='copyright_by',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='copyright_on',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='created_by',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='created_on',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='modified_by',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='modified_on',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='reviewed_by',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='reviewed_on',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_file',
            field=models.FileField(max_length=500, upload_to=backend.models.Content.set_file_name, validators=[backend.validators.validate_unique_filename], verbose_name='File'),
        ),
    ]
