# Generated by Django 3.0.4 on 2021-07-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210629_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='reviewed',
            field=models.BooleanField(default=0),
        ),
    ]
