# Generated by Django 3.0.4 on 2021-07-13 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_content_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='reviewed_on',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
