# Generated by Django 3.0.4 on 2021-06-23 05:17

import backend.models
import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210621_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='active',
        ),
        migrations.RemoveField(
            model_name='content',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='content',
            name='copyright_approved',
        ),
        migrations.RemoveField(
            model_name='content',
            name='copyright_by',
        ),
        migrations.RemoveField(
            model_name='content',
            name='copyright_on',
        ),
        migrations.RemoveField(
            model_name='content',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='content',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='content',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='content',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='content',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='content',
            name='reviewed_on',
        ),
        migrations.AlterField(
            model_name='content',
            name='content_file',
            field=models.FileField(max_length=500, upload_to=backend.models.Content.set_file_name, validators=[backend.validators.validate_unique_filename, backend.validators.validate_unique_file], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='content',
            name='filesize',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
