# Generated by Django 3.0.4 on 2021-07-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210713_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='hash',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
