# Generated by Django 3.0.4 on 2021-07-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='copyright_site',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='original_source',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Archive', 'Archive'), ('Deaccession', 'Deaccession'), ('Review', 'Review')], default='Active', max_length=32),
        ),
    ]
