# Generated by Django 3.0.4 on 2021-09-21 23:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0014_update_reviewed_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('website', models.CharField(max_length=2048, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='original_source',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CopyrightPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_contacted', models.DateField(default=datetime.date.today, null=True)),
                ('granted', models.BooleanField(default=False)),
                ('date_of_response', models.DateField(default=datetime.date.today, null=True)),
                ('description', models.TextField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Organization')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
