# Generated by Django 3.0.4 on 2021-11-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_content_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='display_title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
