# Generated by Django 3.0.4 on 2022-03-30 14:52

import backend.models
import backend.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_clamd.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0017_content_display_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='rights_statement',
        ),
        migrations.AlterField(
            model_name='content',
            name='content_file',
            field=models.FileField(max_length=500, upload_to=backend.models.Content.set_file_name, validators=[backend.validators.validate_unique_filename, django_clamd.validators.validate_file_infection], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='content',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='content_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='content',
            name='reviewed_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='content_reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
