# Generated by Django 3.0.4 on 2022-05-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_content_reviewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='original_source',
            field=models.TextField(null=True),
        ),
    ]
